adminPassword: "admin-secret" # Set a secure password for Grafana admin user

# Configure Prometheus data source
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc:80
      access: proxy
      isDefault: true
      editable: true

# Enable dashboard provisioning
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# Define dashboards via ConfigMap
dashboards:
  default:
    hubble-metrics:
      gnetId: null
      datasource: Prometheus
      json: |
        {
          "annotations": {
            "list": []
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "links": [],
          "panels": [
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
              "id": 1,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "sum(rate(hubble_flows_processed_total{destination_workload=~\"backend|celery-worker|data-extractor|ocr-service|postgres|redis\",destination_namespace=\"default\"}[1m])) by (destination_namespace, destination_workload)",
                  "legendFormat": "{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Hubble Flows per Workload (default)",
              "type": "graph",
              "yaxes": [
                { "format": "short", "label": "Flows/s", "logBase": 1, "max": null, "min": null, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            },
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
              "id": 2,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "sum(rate(hubble_flows_processed_total{destination_workload=~\"$destination_workload\",destination_namespace=\"default\"}[1m])) by (destination_workload) / (count by (destination_workload) (label_replace(kube_pod_owner{owner_kind=~\"(ReplicaSet|StatefulSet)\", namespace=\"default\"},\"destination_workload\", \"$1\", \"owner_name\", \"^(.*)-[a-z0-9]+$\")) or vector(1))",
                  "legendFormat": "{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Hubble Flows per Pod (default)",
              "type": "graph",
              "yaxes": [
                { "format": "short", "label": "Flows/s/pod", "logBase": 1, "max": null, "min": null, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            },
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
              "id": 3,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "histogram_quantile(0.95, sum(rate(hubble_http_request_duration_seconds_bucket{destination_namespace=\"default\"}[1m])) by (le, destination_workload))",
                  "legendFormat": "{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Hubble HTTP Request Latency (P95, default)",
              "type": "graph",
              "yaxes": [
                { "format": "s", "label": "Seconds", "logBase": 1, "max": null, "min": null, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            },
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
              "id": 4,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "sum(rate(hubble_http_requests_total{status=~\"5..\",destination_namespace=\"default\"}[1m])) by (destination_workload) > 0 or vector(0)  / (sum(rate(hubble_http_requests_total{destination_namespace=\"default\"}[1m])) by (destination_workload) > 0 or vector(1))",
                  "legendFormat": "{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Hubble HTTP 5xx Response Ratio (default)",
              "type": "graph",
              "yaxes": [
                { "format": "percentunit", "label": "Ratio", "logBase": 1, "max": 1, "min": 0, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            }
          ],
          "schemaVersion": 36,
          "style": "dark",
          "tags": ["network", "hubble"],
          "templating": {
            "list": [
              {
                "allValue": null,
                "current": {},
                "datasource": "Prometheus",
                "definition": "label_values(hubble_flows_processed_total{destination_namespace=\"default\",destination_workload=~\"backend|celery-worker|data-extractor|ocr-service|postgres|redis\"}, destination_workload)",
                "hide": 0,
                "includeAll": true,
                "label": "Workload",
                "multi": true,
                "name": "destination_workload",
                "options": [],
                "query": {
                  "query": "label_values(hubble_flows_processed_total{destination_namespace=\"default\",destination_workload=~\"backend|celery-worker|data-extractor|ocr-service|postgres|redis\"}, destination_workload)",
                  "refId": "Prometheus-destination_workload-Variable-Query"
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              }
            ]
          },
          "time": {
            "from": "now-6h",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": ["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"],
            "time_options": ["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"]
          },
          "timezone": "",
          "title": "Hubble Metrics Dashboard (default)",
          "uid": "hubble-metrics",
          "version": 1
        }
    istio-metrics:
      gnetId: null
      datasource: Prometheus
      json: |
        {
          "annotations": {
            "list": []
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "links": [],
          "panels": [
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
              "id": 1,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload_namespace, destination_workload)",
                  "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Istio Requests per Workload",
              "type": "graph",
              "yaxes": [
                { "format": "short", "label": "Requests/s", "logBase": 1, "max": null, "min": null, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            },
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
              "id": 2,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload)/ (count by (destination_workload) (label_replace(kube_pod_owner{owner_kind=~\"(ReplicaSet|StatefulSet)\", namespace=~\"$destination_workload_namespace\"},\"destination_workload\", \"$1\", \"owner_name\", \"^(.*)-[a-z0-9]+$\")) or vector(1))",
                  "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Istio Requests per Pod",
              "type": "graph",
              "yaxes": [
                { "format": "short", "label": "Requests/s/pod", "logBase": 1, "max": null, "min": null, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            },
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
              "id": 3,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (le, destination_workload_namespace, destination_workload))",
                  "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Istio Request Latency (P95)",
              "type": "graph",
              "yaxes": [
                { "format": "ms", "label": "Milliseconds", "logBase": 1, "max": null, "min": null, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            },
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "fillGradient": 0,
              "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
              "id": 4,
              "legend": { "avg": false, "current": true, "max": false, "min": false, "show": true, "total": false, "values": true },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": { "alertThreshold": true },
              "targets": [
                {
                  "expr": "sum(rate(istio_requests_total{response_code=~\"5..\",destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload_namespace, destination_workload) / (sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload_namespace, destination_workload) > 0 or vector(0))",
                  "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}",
                  "refId": "A"
                }
              ],
              "title": "Istio 5xx Error Ratio",
              "type": "graph",
              "yaxes": [
                { "format": "percentunit", "label": "Ratio", "logBase": 1, "max": 1, "min": 0, "show": true },
                { "format": "short", "label": null, "logBase": 1, "max": null, "min": null, "show": true }
              ]
            }
          ],
          "schemaVersion": 36,
          "style": "dark",
          "tags": ["network", "istio"],
          "templating": {
            "list": [
              {
                "allValue": null,
                "current": {},
                "datasource": "Prometheus",
                "definition": "label_values(istio_requests_total, destination_workload_namespace)",
                "hide": 0,
                "includeAll": true,
                "label": "Istio Namespace",
                "multi": true,
                "name": "destination_workload_namespace",
                "options": [],
                "query": {
                  "query": "label_values(istio_requests_total, destination_workload_namespace)",
                  "refId": "Prometheus-destination_workload_namespace-Variable-Query"
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              },
              {
                "allValue": null,
                "current": {},
                "datasource": "Prometheus",
                "definition": "label_values(istio_requests_total{destination_workload_namespace=~\"$destination_workload_namespace\"}, destination_workload)",
                "hide": 0,
                "includeAll": true,
                "label": "Istio Workload",
                "multi": true,
                "name": "destination_workload",
                "options": [],
                "query": {
                  "query": "label_values(istio_requests_total{destination_workload_namespace=~\"$destination_workload_namespace\"}, destination_workload)",
                  "refId": "Prometheus-destination_workload-Variable-Query"
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              }
            ]
          },
          "time": {
            "from": "now-6h",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": ["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"],
            "time_options": ["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"]
          },
          "timezone": "",
          "title": "Istio Metrics Dashboard",
          "uid": "istio-metrics",
          "version": 1
        }

# Configure Grafana service
service:
  type: ClusterIP
  port: 80

# Enable persistence (optional, for storing Grafana configuration)
persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard