{
 "title": "Hubble Metrics Dashboard (default)",
 "tags": [
  "network",
  "hubble"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "destination_workload",
    "label": "Workload",
    "query": {
     "query": "label_values(hubble_flows_processed_total{destination_namespace=\"default\",destination_workload=~\"backend|celery-coordinator|data-extractor|ocr-worker|postgres|redis\"}, destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hubble Flows per Workload (default)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{destination_workload=~\"backend|celery-coordinator|data-extractor|ocr-worker|postgres|redis\",destination_namespace=\"default\"}[30s])) by (destination_namespace, destination_workload)",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble Flows per Pod (default)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{destination_workload=~\"backend|celery-coordinator|data-extractor|ocr-worker|postgres|redis\",destination_namespace=\"default\"}[30s])) by (destination_workload) / (count by (destination_workload) (label_replace(kube_pod_owner{owner_kind=~\"(ReplicaSet|StatefulSet)\", namespace=\"default\"},\"destination_workload\", \"$1\", \"owner_name\", \"^(.*)-[a-z0-9]+$\")) or vector(1))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble HTTP Request Latency (P95, default)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, destination_workload) (\n    label_replace(\n      rate(hubble_http_request_duration_seconds_bucket{destination_namespace=\"default\"}[30s]),\n      \"destination_workload\",\n      \"backend\",\n      \"destination_workload\",\n      \"^$\"\n    )\n  )\n)\n",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble HTTP 5xx Response Ratio (default)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_http_requests_total{status=~\"5..\",destination_namespace=\"default\"}[30s])) by (destination_workload) > 0 or vector(0)  / (sum(rate(hubble_http_requests_total{destination_namespace=\"default\"}[30s])) by (destination_workload) > 0 or vector(1))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble HTTP Request Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (destination_workload) (\n  label_replace(\n    rate(hubble_http_request_duration_seconds_sum{destination_namespace=\"default\"}[30s]),\n    \"destination_workload\", \n    \"backend\", \n    \"destination_workload\", \n    \"^$\"\n  )\n) \n/ \nsum by (destination_workload) (\n  label_replace(\n    rate(hubble_http_request_duration_seconds_count{destination_namespace=\"default\"}[30s]),\n    \"destination_workload\", \n    \"backend\", \n    \"destination_workload\", \n    \"^$\"\n  )\n)\n",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  }
 ]
}
{
 "title": "Istio Metrics Dashboard",
 "tags": [
  "network",
  "istio"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "destination_workload_namespace",
    "label": "Istio Namespace",
    "query": {
     "query": "label_values(istio_requests_total{=\"default\"}, destination_workload_namespace)"
    }
   },
   {
    "name": "destination_workload",
    "label": "Istio Workload",
    "query": {
     "query": "label_values(istio_requests_total{destination_workload_namespace=~\"$destination_workload_namespace\"}, destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Istio Requests per Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[30s])) by (destination_workload_namespace, destination_workload)",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio Requests per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[30s])) by (destination_workload)/ (count by (destination_workload) (label_replace(kube_pod_owner{owner_kind=~\"(ReplicaSet|StatefulSet)\", namespace=~\"$destination_workload_namespace\"},\"destination_workload\", \"$1\", \"owner_name\", \"^(.*)-[a-z0-9]+$\")) or vector(1))",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio Request Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\",le!~\"3600000|1800000|600000.0|300000.0\"}[30s])) by (le, destination_workload_namespace, destination_workload))",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio 5xx Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"5..\",destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[30s])) by (destination_workload_namespace, destination_workload) / (sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[30s])) by (destination_workload_namespace, destination_workload) > 0 or vector(0))",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio Request Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{destination_workload!=\"\", destination_workload_namespace=~\"$destination_workload_namespace\"}[30s])) by (destination_workload_namespace, destination_workload)\n/\nsum(rate(istio_request_duration_milliseconds_count{destination_workload!=\"\", destination_workload_namespace=~\"$destination_workload_namespace\"}[30s])) by (destination_workload_namespace, destination_workload)\n",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  }
 ]
}
{
 "title": "HPA Load Testing Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "hpa",
    "query": "label_values(kube_hpa_status_current_replicas{namespace=\"default\"}, horizontalpodautoscaler)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average End to End Task Duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(invoice_chain_duration_seconds_sum[30s]))\n/\nsum(rate(invoice_chain_duration_seconds_count[30s]))\n",
     "legendFormat": "Average Invoice Task Duration"
    }
   ]
  },
  {
   "title": "Average Celery Tasks Duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flower_task_runtime_seconds_sum[30s])) by (task)\n/\nsum(rate(flower_task_runtime_seconds_count[30s])) by (task)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaling Latency - Desired vs Current Replicas (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"default\",horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - Current Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"default\",horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - Desired Replicas"
    }
   ]
  },
  {
   "title": "CPU Utilization (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[30s]), \"workload\", \"$1\", \"pod\", \"^(.*)-[a-z0-9]+-[a-z0-9]+$\")\n) by (workload)\n/\nsum(\n  label_replace(kube_pod_container_resource_requests{namespace=\"default\", resource=\"cpu\"}, \"workload\", \"$1\", \"pod\", \"^(.*)-[a-z0-9]+-[a-z0-9]+$\")\n) by (workload)\n* 100\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(rate(container_memory_usage_bytes{namespace=\"default\"}[30s]), \"workload\", \"$1\", \"pod\", \"^(.*)-[a-z0-9]+-[a-z0-9]+$\")\n) by (workload)\n/\nsum(\n  label_replace(kube_pod_container_resource_requests{namespace=\"default\", resource=\"memory\"}, \"workload\", \"$1\", \"pod\", \"^(.*)-[a-z0-9]+-[a-z0-9]+$\")\n) by (workload)\n* 100\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# sum(container_memory_usage_bytes{namespace=\"default\"}) by (pod)\nsum(label_replace(rate(container_memory_usage_bytes{namespace=\"default\"}[30s]),\"workload\",\"$1\",\"pod\",\"^(.*)-[a-z0-9]+-[a-z0-9]+$\")) by (workload)\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[30s]),\"workload\",\"$1\",\"pod\",\"^(.*)-[a-z0-9]+-[a-z0-9]+$\")) by (workload)\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory Provisioning Ratio (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": " (sum(label_replace(avg_over_time(container_memory_usage_bytes{namespace=\"default\"}[5m]),\"workload\",\"$1\",\"pod\",\"^(.*)-[a-z0-9]+-[a-z0-9]+$\")) by (workload) > 0 or vector(1)) / sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"default\"},\"workload\",\"$1\",\"pod\",\"^(.*)-[a-z0-9]+-[a-z0-9]+$\")) by (workload)",
     "legendFormat": "{{workload}} "
    }
   ]
  },
  {
   "title": "CPU Provisioning Ratio (All Workloads in default)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": " sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[30s]),\"workload\",\"$1\",\"pod\",\"^(.*)-[a-z0-9]+-[a-z0-9]+$\")) by (workload) / sum(label_replace(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"default\"},\"workload\",\"$1\",\"pod\",\"^(.*)-[a-z0-9]+-[a-z0-9]+$\")) by (workload)",
     "legendFormat": "{{workload}} "
    }
   ]
  }
 ]
}