{
 "title": "Hubble Metrics Dashboard (default)",
 "tags": [
  "network",
  "hubble"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "destination_workload",
    "label": "Workload",
    "query": {
     "query": "label_values(hubble_flows_processed_total{destination_namespace=\"default\",destination_workload=~\"backend|celery-worker|data-extractor|ocr-service|postgres|redis\"}, destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hubble Flows per Workload (default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Flows/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{destination_workload=~\"backend|celery-worker|data-extractor|ocr-service|postgres|redis\",destination_namespace=\"default\"}[1m])) by (destination_namespace, destination_workload)",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble Flows per Pod (default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Flows/s/pod" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{destination_workload=~\"$destination_workload\",destination_namespace=\"default\"}[1m])) by (destination_workload) / (count by (destination_workload) (label_replace(kube_pod_owner{owner_kind=~\"(ReplicaSet|StatefulSet)\", namespace=\"default\"},\"destination_workload\", \"$1\", \"owner_name\", \"^(.*)-[a-z0-9]+$\")) or vector(1))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble HTTP Request Latency (P95, default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hubble_http_request_duration_seconds_bucket{destination_namespace=\"default\"}[1m])) by (le, destination_workload))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Hubble HTTP 5xx Response Ratio (default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "Ratio" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_http_requests_total{status=~\"5..\",destination_namespace=\"default\"}[1m])) by (destination_workload) > 0 or vector(0)  / (sum(rate(hubble_http_requests_total{destination_namespace=\"default\"}[1m])) by (destination_workload) > 0 or vector(1))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  }
 ]
}
{
 "title": "Istio Metrics Dashboard",
 "tags": [
  "network",
  "istio"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "destination_workload_namespace",
    "label": "Istio Namespace",
    "query": {
     "query": "label_values(istio_requests_total, destination_workload_namespace)"
    }
   },
   {
    "name": "destination_workload",
    "label": "Istio Workload",
    "query": {
     "query": "label_values(istio_requests_total{destination_workload_namespace=~\"$destination_workload_namespace\"}, destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Istio Requests per Workload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload_namespace, destination_workload)",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio Requests per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests/s/pod" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload)/ (count by (destination_workload) (label_replace(kube_pod_owner{owner_kind=~\"(ReplicaSet|StatefulSet)\", namespace=~\"$destination_workload_namespace\"},\"destination_workload\", \"$1\", \"owner_name\", \"^(.*)-[a-z0-9]+$\")) or vector(1))",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio Request Latency (P95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (le, destination_workload_namespace, destination_workload))",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio 5xx Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "Ratio" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"5..\",destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload_namespace, destination_workload) / (sum(rate(istio_requests_total{destination_workload!=\"\",destination_workload_namespace=~\"$destination_workload_namespace\"}[1m])) by (destination_workload_namespace, destination_workload) > 0 or vector(0))",
     "legendFormat": "{{destination_workload_namespace}}/{{destination_workload}}"
    }
   ]
  }
 ]
}