apiVersion: telemetry.istio.io/v1beta1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: "istio_request_duration_milliseconds"
      histogram:
        - 100
        - 500
        - 1000
        - 5000
        - 10000
        - 30000
        - 60000
        - 70000
        - 100000
        - 150000
