apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: parszyk/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: redis://redis:6379/0
        - name: OCR_URL
          value: http://ocr-service:9090/ocr
        - name: EXTRACTOR_URL
          value: http://data-extractor-service:8000/generate
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
