---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: {{ .Values.celeryCoordinator.replicas }}
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
      annotations:
{{- if .Values.istio.enabled }}
        "sidecar.istio.io/inject": "true"
{{- end }}
    spec:
      containers:
      - name: worker
        image: {{ .Values.celeryCoordinator.image.repository }}:{{ .Values.celeryCoordinator.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["celery", "-A", "tasks", "flower", "--port=5555"]
        ports:
        - name: http
          containerPort: 5555
        env:
        - name: REDIS_URL
          value: redis://redis:{{ .Values.redis.port }}/0
        - name: EXTRACTOR_URL
          value: http://data-extractor-service:{{ .Values.dataExtractor.port }}/parse-invoice
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: flower-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5555'
spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: http
  type: LoadBalancer
