# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: ocr-service-hpa
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: ocr-service
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Object
#       object:
#         describedObject:
#           apiVersion: apps/v1
#           kind: Deployment
#           name: ocr-service
#         metric:
#           name: hubble_flows_per_pod
#         target:
#           type: Value
#           value: "150m"  # Scale up if flows per pod exceed 0.15 (150 milli)
#     - type: Object
#       object:
#         describedObject:
#           apiVersion: apps/v1
#           kind: Deployment
#           name: ocr-service
#         metric:
#           name: hubble_http_request_latency_p95
#         target:
#           type: Value
#           value: "500m"  # Scale up if 95th percentile latency exceeds 500ms
#     - type: Object
#       object:
#         describedObject:
#           apiVersion: apps/v1
#           kind: Deployment
#           name: ocr-service
#         metric:
#           name: hubble_http_5XX_response_ratio
#         target:
#           type: Value
#           value: "0.01"  # Scale up if 5xx error ratio exceeds 1%