{{- if .Values.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-visibility"
spec:
  endpointSelector:
    matchLabels:
      "k8s:io.kubernetes.pod.namespace": default
  ingress:
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": default
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "{{ .Values.backend.port }}"
        protocol: TCP
      - port: "{{ .Values.backend.servicePort }}"
        protocol: TCP
      - port: "{{ .Values.dataExtractor.port }}"
        protocol: TCP
      rules:
        http: [{}]
    - ports:
      - port: "{{ .Values.redis.port }}"
        protocol: TCP
      - port: "{{ .Values.postgres.port }}"
        protocol: TCP
  - fromEntities:
      - world
    toPorts:
      - ports:
        - port: "{{ .Values.backend.port }}"
          protocol: TCP

  egress:
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": default
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "{{ .Values.backend.port }}"
        protocol: TCP
      - port: "{{ .Values.backend.servicePort }}"
        protocol: TCP
      - port: "{{ .Values.dataExtractor.port }}"
        protocol: TCP
      rules:
        http: [{}]
    - ports:
      - port: "{{ .Values.postgres.port }}"
        protocol: TCP
      - port: "{{ .Values.redis.port }}"
        protocol: TCP
  - toEntities:
    - world
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "debug-allow-all"
  namespace: default 
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - all
  egress:
    - toEntities:
        - all
{{- end }}
