{{- if .Values.istio.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: label-namespace-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      serviceAccountName: label-namespace
      containers:
      - name: label
        image: bitnami/kubectl:1.30
        command: ["sh", "-c"]
        args:
          - kubectl label namespace {{ .Release.Namespace }} istio-injection=enabled --overwrite
      restartPolicy: OnFailure
{{- end }}
