apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
      annotations:
{{- if .Values.istio.enabled }}
        "sidecar.istio.io/inject": "true"
{{- end }}
    spec:
      containers:
      - name: ocr
        image: {{ .Values.ocrService.image.repository }}:{{ .Values.ocrService.image.tag }}
        ports:
        - containerPort: {{ .Values.ocrService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  selector:
    app: ocr
  ports:
    - protocol: TCP
      port: {{ .Values.ocrService.port }}
      targetPort: {{ .Values.ocrService.port }}
  type: ClusterIP