apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
      annotations:
{{- if .Values.istio.enabled }}
        "sidecar.istio.io/inject": "true"
{{- end }}
    spec:
      containers:
      - name: ocr
        image: {{ .Values.ocrService.image.repository }}:{{ .Values.ocrService.image.tag }}
        ports:
        - containerPort: {{ .Values.ocrService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  selector:
    app: ocr
  ports:
    - protocol: TCP
      port: {{ .Values.ocrService.port }}
      targetPort: {{ .Values.ocrService.port }}
  type: ClusterIP

{{- if .Values.ocrService.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ocr-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ocr-service
  minReplicas: 1
  maxReplicas: {{ .Values.ocrService.maxReplicas | default 1}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ocrService.hpa.cpuTarget | default 80 }} # Scale if CPU usage exceeds 80%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ocrService.hpa.memoryTarget | default 80 }} # Scale if memory usage exceeds 80%
{{- if .Values.cilium.enabled }}
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ocr-service
        metric:
          name: hubble_flows_per_pod
        target:
          type: Value
          value: "150m"  # Scale up if flows per pod exceed 0.15 (150 milli)
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ocr-service
        metric:
          name: hubble_http_request_latency_p95
        target:
          type: Value
          value: "500m"  # Scale up if 95th percentile latency exceeds 500ms
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ocr-service
        metric:
          name: hubble_http_5XX_response_ratio
        target:
          type: Value
          value: "0.01"  # Scale up if 5xx error ratio exceeds 1%
{{- end }}
{{- if .Values.istio.enabled }}
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ocr-service
        metric:
          name: istio_requests_per_pod
        target:
          type: Value
          value: "150m"  # Scale up if flows per pod exceed 0.15 (150 milli)
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ocr-service
        metric:
          name: istio_request_latency_p95
        target:
          type: Value
          value: "500m"  # Scale up if 95th percentile latency exceeds 500ms
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ocr-service
        metric:
          name: istio_5xx_error_ratio
        target:
          type: Value
          value: "0.01"  # Scale up if 5xx error ratio exceeds 1%
{{- end }}
{{- end }}