# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusAdapter
# metadata:
#   name: prometheus-adapter
# spec:
#   rules:
#   - seriesQuery: 'hubble_flows_processed_total{destination_workload!="",destination_namespace!=""}'
#     resources:
#       overrides:
#         destination_namespace: {resource: "namespace"}
#         destination_workload: {resource: "pod"}
#     name:
#       matches: "^hubble_flows_processed_total$"
#       as: "hubble_flows_per_workload"
#     metricsQuery: 'sum(rate(hubble_flows_processed_total{<<.LabelMatchers>>,destination_workload!="",destination_namespace!=""}[1m])) by (destination_namespace, destination_workload)'
#   - seriesQuery: 'istio_requests_total{destination_workload!="",destination_workload_namespace!=""}'
#     resources:
#       overrides:
#         destination_workload_namespace: {resource: "namespace"}
#         destination_workload: {resource: "pod"}
#     name:
#       matches: "^istio_requests_total$"
#       as: "istio_requests_per_workload"
#     metricsQuery: 'sum(rate(istio_requests_total{<<.LabelMatchers>>,destination_workload!="",destination_workload_namespace!=""}[1m])) by (destination_workload_namespace, destination_workload)'
#   - seriesQuery: 'istio_request_duration_milliseconds_bucket{destination_workload!="",destination_workload_namespace!=""}'
#     resources:
#       overrides:
#         destination_workload_namespace: {resource: "namespace"}
#         destination_workload: {resource: "pod"}
#     name:
#       matches: "^istio_request_duration_milliseconds_bucket$"
#       as: "istio_request_duration_p95"
#     metricsQuery: 'histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{<<.LabelMatchers>>,destination_workload!="",destination_workload_namespace!=""}[1m])) by (le, destination_workload_namespace, destination_workload))'
# # apiVersion: v1
# # kind: ConfigMap
# # metadata:
# #   name: prometheus-adapter
# #   namespace: monitoring
# # data:
# #   config.yaml: |
# #     rules:
# #       default: false

# #       custom:
# #         - seriesQuery: 'hubble_flows_processed_total{destination_workload!=""}'
# #           resources:
# #             overrides:
# #               destination_workload: {resource: "pod"}  # Could be "deployment" or "workload" depending on your use
# #               destination_namespace: {resource: "namespace"}
# #           name:
# #             matches: "hubble_flows_processed_total"
# #             as: "hubble_flows_per_workload"
# #           metricsQuery: 'sum(rate(hubble_flows_processed_total{<<.LabelMatchers>>}[1m])) by (destination_namespace, destination_workload)'

# #         - seriesQuery: 'istio_requests_total{destination_workload!=""}'
# #           resources:
# #             overrides:
# #               destination_workload: {resource: "pod"}
# #               destination_workload_namespace: {resource: "namespace"}
# #           name:
# #             matches: "istio_requests_total"
# #             as: "istio_requests_per_workload"
# #           metricsQuery: 'sum(rate(istio_requests_total{<<.LabelMatchers>>}[1m])) by (destination_workload_namespace, destination_workload)'

# #         - seriesQuery: 'istio_request_duration_milliseconds_bucket{destination_workload!=""}'
# #           resources:
# #             overrides:
# #               destination_workload: {resource: "pod"}
# #               destination_workload_namespace: {resource: "namespace"}
# #           name:
# #             matches: "istio_request_duration_milliseconds_bucket"
# #             as: "istio_request_duration_p95"
# #           metricsQuery: |
# #             histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{<<.LabelMatchers>>}[1m])) by (le, destination_workload_namespace, destination_workload))

# # #     rules:
# # #     # Istio Metrics
# # #     - seriesQuery: 'istio_requests_total{destination_workload="podinfo", destination_workload_namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #           destination_workload: {resource: "pod"}
# # #       name:
# # #         matches: "^istio_requests_total$"
# # #         as: "istio_requests_per_pod"
# # #       metricsQuery: |
# # #         sum(rate(istio_requests_total{destination_workload="podinfo", destination_workload_namespace="default"}[1m]))
# # #         /
# # #         count(kube_pod_info{namespace="default", pod=~"podinfo.*"})
# # #     - seriesQuery: 'istio_requests_total{destination_workload="podinfo", destination_workload_namespace="default", response_code=~"5.."}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #           destination_workload: {resource: "pod"}
# # #       name:
# # #         matches: "^istio_requests_total$"
# # #         as: "istio_http_5xx_errors"
# # #       metricsQuery: |
# # #         rate(istio_requests_total{destination_workload="podinfo", destination_workload_namespace="default", response_code=~"5.."}[1m])
# # #     - seriesQuery: 'istio_request_duration_milliseconds_bucket{destination_workload="podinfo", destination_workload_namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #           destination_workload: {resource: "pod"}
# # #       name:
# # #         matches: "^istio_request_duration_milliseconds_bucket$"
# # #         as: "istio_latency_p95"
# # #       metricsQuery: |
# # #         histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload="podinfo", destination_workload_namespace="default"}[1m])) by (le))
    
# # #     # Cilium Metrics
# # #     - seriesQuery: 'hubble_flows_processed_total{to=~"podinfo.*", namespace="default", protocol="HTTP"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #           to: {resource: "pod"}
# # #       name:
# # #         matches: "^hubble_flows_processed_total$"
# # #         as: "hubble_requests_per_pod"
# # #       metricsQuery: |
# # #         sum(rate(hubble_flows_processed_total{to=~"podinfo.*", namespace="default", protocol="HTTP"}[1m]))
# # #         /
# # #         count(kube_pod_info{namespace="default", pod=~"podinfo.*"})
# # #     - seriesQuery: 'hubble_flows_processed_total{to=~"podinfo.*", namespace="default", protocol="HTTP", status=~"5.."}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #           to: {resource: "pod"}
# # #       name:
# # #         matches: "^hubble_flows_processed_total$"
# # #         as: "hubble_http_5xx_errors"
# # #       metricsQuery: |
# # #         rate(hubble_flows_processed_total{to=~"podinfo.*", namespace="default", protocol="HTTP", status=~"5.."}[1m])
# # #     - seriesQuery: 'hubble_flows_latency_seconds_bucket{to=~"podinfo.*", namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #           to: {resource: "pod"}
# # #       name:
# # #         matches: "^hubble_flows_latency_seconds_bucket$"
# # #         as: "hubble_latency_p95"
# # #       metricsQuery: |
# # #         histogram_quantile(0.95, sum(rate(hubble_flows_latency_seconds_bucket{to=~"podinfo.*", namespace="default"}[1m])) by (le))
# # #     - seriesQuery: 'hubble_flows_latency_seconds_bucket{namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #       name:
# # #         matches: "^hubble_flows_latency_seconds_bucket$"
# # #         as: "hubble_flow_latency_p95"
# # #       metricsQuery: |
# # #         histogram_quantile(0.95, sum(rate(hubble_flows_latency_seconds_bucket{namespace="default"}[1m])) by (le))
# # #     - seriesQuery: 'cilium_tcp_retransmissions_total{namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #       name:
# # #         matches: "^cilium_tcp_retransmissions_total$"
# # #         as: "cilium_tcp_retransmissions"
# # #       metricsQuery: |
# # #         rate(cilium_tcp_retransmissions_total{namespace="default"}[1m])
# # #     - seriesQuery: 'cilium_dns_requests_total{namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #       name:
# # #         matches: "^cilium_dns_requests_total$"
# # #         as: "cilium_dns_requests"
# # #       metricsQuery: |
# # #         rate(cilium_dns_requests_total{namespace="default"}[1m])
# # #     - seriesQuery: 'hubble_flows_processed_total{source_namespace="default", namespace="default"}'
# # #       resources:
# # #         overrides:
# # #           namespace: {resource: "namespace"}
# # #       name:
# # #         matches: "^hubble_flows_processed_total$"
# # #         as: "hubble_pod_to_pod_flows"
# # #       metricsQuery: |
# # #         rate(hubble_flows_processed_total{source_namespace="default", namespace="default"}[1m])


# # # # sum(rate(istio_requests_total{destination_workload="backend", destination_workload_namespace="default"}[20m]))
# # # # /
# # # # count(kube_pod_info{namespace="default", pod=~"backend.*"})

# # # #  histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload="backend", destination_workload_namespace="default"}[30m])) by (le))

# # # # sum(rate(istio_request_duration_milliseconds_bucket{destination_workload="backend", destination_workload_namespace="default"}[30m]))

