apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-pvc


---

apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-init
spec:
  template:
    spec:
      containers:
      - name: ollama-init
        image: ollama/ollama
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
        - name: script-volume
          mountPath: /scripts
        command: ["sh", "-c", "/scripts/entrypoint.sh"]
      restartPolicy: OnFailure
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-pvc
      - name: script-volume
        configMap:
          name: ollama-entrypoint-cm
          defaultMode: 0500

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-entrypoint-cm
data:
  entrypoint.sh: |
    #!/bin/bash

    # Start Ollama in the background.
    /bin/ollama serve &

    # Record Process ID.
    pid=$!

    # Pause for Ollama to start.
    sleep 5

    echo "🔴 Retrieve sroecker/nuextract-tiny-v1.5 model..."
    ollama pull sroecker/nuextract-tiny-v1.5
    echo "🟢 Done!"

    # Wait for Ollama process to finish.
    wait $pid
    exit 0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
  type: ClusterIP