global:
  imagePullPolicy: Always #IfNotPresent

istio:
  enabled: false

cilium:
  enabled: false

backend:
  image:
    repository: parszyk/backend
    tag: arch-amd64-test
  replicas: 1
  port: 8080
  nodePort: 30030
  servicePort: 8081
  hpa:
    enabled: true
    maxReplicas: 5

worker:
  image:
    repository: parszyk/backend
    tag: arch-amd64-test
  replicas: 1
  hpa:
    enabled: true
    maxReplicas: 10
  metrics:
    port: 8000

redis:
  image:
    repository: redis
    tag: "7"
  port: 6379

ocrService:
  image:
    repository: parszyk/ocr-service
    tag: arch-amd64
  port: 9090
  hpa:
    enabled: true
    maxReplicas: 25

dataExtractor:
  image:
    repository: parszyk/data-extractor-regex
    tag: arch-amd64
  replicas: 1
  port: 8000
  servicePort: 8000
  hpa:
    enabled: true
    maxReplicas: 10
  env:
    DB_HOST: postgres-service
    DB_NAME: invoices
    DB_USER: postgres
    DB_PASSWORD: mysecretpassword
    DB_PORT: "5432"

postgres:
  image:
    repository: postgres
    tag: "13"
  replicas: 1
  port: 5432
  servicePort: 5432
  pvc:
    size: 1Gi
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_DB: invoices
  initdb:
    enabled: true
    scripts:
      init.sql: |
              CREATE TABLE sellers (
                  id SERIAL PRIMARY KEY,
                  name VARCHAR(255) NOT NULL,
                  address TEXT,
                  tax_id VARCHAR(50) UNIQUE NOT NULL,
                  iban VARCHAR(50),
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );
              CREATE TABLE clients (
                  id SERIAL PRIMARY KEY,
                  name VARCHAR(255) NOT NULL,
                  address TEXT,
                  tax_id VARCHAR(50) UNIQUE NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );
              CREATE TABLE invoices (
                  id SERIAL PRIMARY KEY,
                  invoice_number VARCHAR(50) UNIQUE NOT NULL,
                  issue_date DATE,
                  seller_id INTEGER REFERENCES sellers(id) ON DELETE RESTRICT,
                  client_id INTEGER REFERENCES clients(id) ON DELETE RESTRICT,
                  net_total VARCHAR(20),
                  gross_total VARCHAR(20),
                  vat_rate VARCHAR(10),
                  vat_amount VARCHAR(20),
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );
              CREATE TABLE items (
                  id SERIAL PRIMARY KEY,
                  invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE,
                  description TEXT NOT NULL,
                  quantity VARCHAR(20),
                  unit VARCHAR(50),
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );